apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotty-cow
  labels:
    app: gotty-cow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotty-cow
  template:
    metadata:
      labels:
        app: gotty-cow
    spec:
      containers:
      - name: gotty-cow
        image: lizrice/gotty:kubecon-u
        # imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1000Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: gotty-cow
  labels:
    app: gotty-cow
spec:
  ports:
    - port: 8080
      nodePort: 32333
  selector:
    app: gotty-cow
  type: NodePort
